### ISSUE TITLE
Remix() silently changes dtype to `float32`

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audresample#15]
```python
y = np.random.random((2, 10))
print(y.dtype)
y = audresample.remix(y)
print(y.dtype)
```
```
float64
float32
```

**Comment by hagenw** [comment]
It could be due to

https://github.com/audeering/audresample/blob/master/audresample/core/api.py#L167

whereas before we make sure to copy the signal data type:

https://github.com/audeering/audresample/blob/master/audresample/core/api.py#L143-L146
