### ISSUE TITLE
Support for Apple Devices with M1 chip

### ISSUE THREAD

**Issue by dcleres** [audeering/audresample#21]
Dear team, 

I am currently facing an issue when trying to run OpenSmile on my Mac with an M1 Chip. I get the following error message that seems to be linked to this python package. 

```shell

OSError: dlopen(/Users/davidcleres/miniforge3/envs/resmonics-m1/lib/python3.9/site-packages/audresample/core/bin/libaudresample.dylib, 0x0006): tried: '/opt/homebrew/lib/libaudresample.dylib' (no such file), '/opt/homebrew/lib/libaudresample.dylib' (no such file), '/libaudresample.dylib' (no such file), '/Users/davidcleres/miniforge3/envs/lib/python3.9/site-packages/audresample/core/bin/libaudresample.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))

```

I saw in previous releases that you state that MacOS support was added. Was this tested on Macs with Intel chips or M1 chips or both? I would appreciate your help. Maybe I am doing something wrong. I also tried to install the (https://github.com/audeering/audresamplelib) package from the source. However, this failed as well with the following issue: 

```shell

Release % conan install ..

Configuration:
[settings]
arch=armv8
arch_build=armv8
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=13
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

soxr/0.1.3@audeering/testing: Not found in local cache, looking in remotes...
soxr/0.1.3@audeering/testing: Trying with 'conancenter'...
ERROR: Unable to find 'soxr/0.1.3@audeering/testing' in remotes

```

**Comment by hagenw** [comment]
Unfortunately, we rely on the runners available on Github for doing the tests and M1 is not available yet, compare https://github.com/actions/virtual-environments/issues/2187

**Comment by hagenw** [comment]
We have now made a new release of `audresample` supporting MacOS M1 architecture.
Please update `audresample` with:

```bash
$ pip install --upgrade audresample
```

and try again.

We also have cleaned up the conan recipe in https://github.com/audeering/audresamplelib to be able to build it from source.

As Github has no MacOS M1 runner, we are creating the binaries for `audresample` at the moment in an internal project and our own runner.
